import type { Metadata } from "next";
import "./globals.css";
// import Link from "next/link";
// import { FaHome } from "react-icons/fa";
import Header from "@/components/headers/page";

export const metadata: Metadata = {
  title: "my personal website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`background: 'linear-gradient(135deg, #0F0F0F, #1E1E1E, #FF69B4)  antialiased font-sans`}
      >
        <Header />

        {children}
      </body>
    </html>
  );
}
