import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import { FaHome } from "react-icons/fa";

export const metadata: Metadata = {
  title: "my personal website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`background: 'linear-gradient(135deg, #0F0F0F, #1E1E1E, #FF69B4)  antialiased font-sans`}
      >
        <header className="z-10 mt-1 bg-[#FFC0CB] grid grid-cols-4 w-full py-5 rounded-full max-w-screen mx-auto fixed text-[#222222] text-lg font-semibold">
          <h1 className="col-span-1 h-fit w-fit flex place-items-center ml-2.5 px-3">
            <Link className="hover:bg-[#FF69B4] transition-colors" href="#home">
              <FaHome size={32} />
            </Link>
          </h1>
          <nav className="col-span-2">
            <ul className="flex justify-between items-center h-fit">
              {/* <li className="hover:bg-[#FF69B4] transition-colors">
                <Link href="#home">Home</Link>
              </li> */}
              <li className="hover:bg-[#FF69B4] transition-colors">
                <Link href="#about">About</Link>
              </li>
              <li className="hover:bg-[#FF69B4] transition-colors">
                <Link href="#skills">Skills</Link>
              </li>
              <li className="hover:bg-[#FF69B4] transition-colors">
                <Link href="#projects">Projects</Link>
              </li>
              <li className="hover:bg-[#FF69B4] transition-colors">
                <Link href="#testi">Testimonial</Link>
              </li>
            </ul>
          </nav>
          <nav className="col-span-1  flex justify-end items-center">
            <ul className="bg-[#222222] text-[#FFC0CB] hover:bg-[#FF69B4] transition-colors rounded-full mr-2.5 px-3">
              <li>
                <Link href="#contact">Contact</Link>
              </li>
            </ul>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
